#!/bin/bash
#该脚本是用于产生一个随机的控制器监听端口号
function port() {
    min=$1
    max=$(($2-$min+1))
    num=$(($RANDOM+1000000000)) #增加一个10位的数再求余
    echo $(($num%$max+$min))
}
rand_port=$(port 6600 6700)#端口号范围
function run() {
  echo "listen-port is :" $1
  ryu-manager controller.py --observe-links --ofp-tcp-listen-port $(($1))#$((x)) 将x转为整数
}
run $rand_port
exit 0
